/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/bottomBar` | `/bottomBar`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/create` | `/create`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/DrawerList` | `/DrawerList`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/newpage` | `/newpage`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/topBar` | `/topBar`; params?: Router.UnknownInputParams; } | { pathname: `/see/country`; params?: Router.UnknownInputParams; } | { pathname: `/see`; params?: Router.UnknownInputParams; } | { pathname: `/see/settings`; params?: Router.UnknownInputParams; } | { pathname: `/see/terms`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/bottomBar` | `/bottomBar`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/create` | `/create`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/DrawerList` | `/DrawerList`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/newpage` | `/newpage`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/topBar` | `/topBar`; params?: Router.UnknownOutputParams; } | { pathname: `/see/country`; params?: Router.UnknownOutputParams; } | { pathname: `/see`; params?: Router.UnknownOutputParams; } | { pathname: `/see/settings`; params?: Router.UnknownOutputParams; } | { pathname: `/see/terms`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/bottomBar${`?${string}` | `#${string}` | ''}` | `/bottomBar${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/create${`?${string}` | `#${string}` | ''}` | `/create${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/DrawerList${`?${string}` | `#${string}` | ''}` | `/DrawerList${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/explore${`?${string}` | `#${string}` | ''}` | `/explore${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/newpage${`?${string}` | `#${string}` | ''}` | `/newpage${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/topBar${`?${string}` | `#${string}` | ''}` | `/topBar${`?${string}` | `#${string}` | ''}` | `/see/country${`?${string}` | `#${string}` | ''}` | `/see${`?${string}` | `#${string}` | ''}` | `/see/settings${`?${string}` | `#${string}` | ''}` | `/see/terms${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/bottomBar` | `/bottomBar`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/create` | `/create`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/DrawerList` | `/DrawerList`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/newpage` | `/newpage`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/topBar` | `/topBar`; params?: Router.UnknownInputParams; } | { pathname: `/see/country`; params?: Router.UnknownInputParams; } | { pathname: `/see`; params?: Router.UnknownInputParams; } | { pathname: `/see/settings`; params?: Router.UnknownInputParams; } | { pathname: `/see/terms`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
